### ISSUE TITLE
Apple Silicon (M1) support

### ISSUE THREAD

**Issue by 0bmxa** [meinardmueller/libtsm#2]
Hello,

`libtsm` fails to install (via `pip`) on a Mac with an Apple Silicon ARM CPU.

Not sure if there will be other issues as well, but for now it seems to be the dependency onto `llvmlite`/`numba`, which don't support Apple Silicon yet, see: https://github.com/numba/llvmlite/issues/799.

Here's the error I'm seeing:
```
Building wheels for collected packages: numba, llvmlite
  Building wheel for numba (setup.py) ... done
  Created wheel for numba: filename=numba-0.55.1-cp39-cp39-macosx_12_0_arm64.whl size=2307917 sha256=[hash]
  Stored in directory: /Users/[user]/Library/Caches/pip/wheels/60/f4/43/[hash]
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error
```

I opened this issue here to track Apple Silicon support, but as it doesn't seem to be an issue with `libtsm` itself, feel free to close it.

Thanks!

**Comment by sebastianrosenzweig** [comment]
Thanks, Max, for raising this issue! 
It seems that support for Numba is coming in the next release, so I'll leave the issue open and try to upgrade to the compatible version as soon as it is available.

**Comment by simonschwaer** [comment]
No longer relevant since Numba is now available for arm64 (and is no longer a dependency of `libtsm`).
